# Generated by Django 4.1.3 on 2022-12-01 14:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.PositiveIntegerField(
                        primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "tel_number",
                    models.IntegerField(
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Invalid number format", regex="^7[0-9]{10}$"
                            )
                        ]
                    ),
                ),
                ("operator_code", models.PositiveIntegerField()),
                ("tag", models.CharField(max_length=255)),
                (
                    "utc",
                    models.CharField(
                        max_length=6,
                        validators=[
                            django.core.validators.RegexValidator(
                                message='Invalid timezone format. Example: "UTC+10"',
                                regex="^UTC[-12-14]{1}$",
                            )
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Distribution",
            fields=[
                (
                    "id",
                    models.PositiveIntegerField(
                        primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("mailing_start", models.DateTimeField()),
                ("message", models.TextField()),
                ("filter", models.JSONField()),
                ("mailing_stop", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.PositiveIntegerField(
                        primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("creating_date", models.DateTimeField()),
                ("status", models.CharField(max_length=255)),
                (
                    "client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clients",
                        related_query_name="client",
                        to="notifications_api.client",
                    ),
                ),
                (
                    "distribution_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distrs",
                        related_query_name="distr",
                        to="notifications_api.distribution",
                    ),
                ),
            ],
        ),
    ]
