# Generated by Django 4.1.3 on 2022-12-02 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="distribution",
            old_name="message",
            new_name="message_text",
        ),
    ]
