# Generated by Django 4.1.3 on 2022-12-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications_api", "0002_rename_message_distribution_message_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="tag",
            field=models.CharField(max_length=10),
        ),
    ]
