# Generated by Django 4.1.3 on 2022-12-02 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications_api", "0003_alter_client_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="utc",
            field=models.CharField(
                max_length=6,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Invalid timezone format. Example: UTC+10",
                        regex="UTC(|(\\+|-)([0-9]|1{1}[0-4]{1}))$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
