# Generated by Django 4.1.3 on 2022-12-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications_api", "0004_alter_client_id_alter_client_utc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
