# Generated by Django 4.1.3 on 2022-12-03 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications_api", "0005_alter_client_id_alter_distribution_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="client_id",
            new_name="client",
        ),
        migrations.RenameField(
            model_name="message",
            old_name="distribution_id",
            new_name="distribution",
        ),
    ]
