# Generated by Django 4.1.3 on 2022-12-03 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("notifications_api", "0006_rename_client_id_message_client_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="msgs",
                related_query_name="msg",
                to="notifications_api.client",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="distribution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="msgs",
                related_query_name="msg",
                to="notifications_api.distribution",
            ),
        ),
    ]
